name: Deploy test site
on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "build ID from integration.yml"
        required: true
      artifact_name:
        description: "artifact ID from integration.yml"
        required: true
        default: "published-app"
env:
  AZURE_WEBAPP_NAME: test-app
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Determine artifact id from run
        id: get-artifact
        run: |
          run_id="${{ github.event.inputs.build_run_id }}"
          artifact_name="${{ github.event.inputs.artifact_name }}"
          api_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/artifacts"
          echo "Querying $api_url" >&2
          artifact_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$api_url" | jq -r --arg name "$artifact_name" '.artifacts[] | select(.name==$name) | .id')
          if [ -z "$artifact_id" ] || [ "$artifact_id" = "null" ]; then
            echo "Artifact '$artifact_name' not found in run $run_id" >&2
            exit 1
          fi
          echo "artifact_id=$artifact_id" >> $GITHUB_OUTPUT

      - name: Download artifact zip
        run: |
          artifact_id=${{ steps.get-artifact.outputs.artifact_id }}
          url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o artifact.zip "$url"
          mkdir -p publish
          unzip -q artifact.zip -d publish

      - name: List published files
        run: ls -la publish

      - name: Deploy to Azure Web App (example)
        if: always()
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish