name: Build test site
run-name: ${{ github.sha }} commit building
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - uses: actions/checkout@v5
      - name: setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore
      - name: Publish
        run: |
          dotnet publish azure-app-service.csproj \
            --configuration Release \
            --output ./publish \
            --runtime linux-x64
      - name: Upload publish folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: published-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'test-app'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}