name: Build test site
run-name: ${{ github.sha }} commit building
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - uses: actions/checkout@v5
      - name: setup dotnet ${{ matrix.dotnet-version }}
        
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Publish
        run: |
          dotnet publish azure-app-service.csproj \
            --configuration Release \
            --output ${{env.DOTNET_ROOT}}/publish \
            --runtime linux-x64
          
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: .published-app
          path: ${{env.DOTNET_ROOT}}/publish
  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .published-app
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-app'
          slot-name: 'stage'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
      - name: logout
        run: |
          az logout